name: Build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.102'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Publish
        run: dotnet publish --no-build --configuration Release
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            bin/Release/net5.0/win10-x64/publish/
