name: Build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.102'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: |
          # NB quite astoundingly dotnet build (or msbuild) sometimes does not correctly
          #    set its exit code, so we have to inspected the output...
          #    see https://github.com/dotnet/msbuild/issues/5689
          #    see https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019
          dotnet build --no-restore --configuration Release -warnAsError -flp:verbosity=detailed -flp:logfile=build.log
          if ((Get-Content -Tail 10 build.log) -notcontains 'Build succeeded.') {
              throw 'dotnet build failed. see the details in build.log'
          }
      - name: Publish
        run: dotnet publish --no-build --configuration Release
      - name: Create Artifacts
        run: |
          Compress-Archive `
            -CompressionLevel Optimal `
            -Path *.ps1,bin/Release/net5.0/win10-x64/publish/* `
            -DestinationPath whoami-web.zip
          Write-Output "$((Get-FileHash whoami-web.zip -Algorithm 'SHA256').Hash) whoami-web.zip"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: |
            whoami-web.zip
